apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
spec:
  containers:
    - name: app-container
      image: your-image:tag
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password