apiVersion: v1
kind: Pod
metadata:
  name: app-multicontainer
spec:
  containers:
    - name: app-container1
      image: your-image1:tag1
      # Container 1 configuration

    - name: app-container2
      image: your-image2:tag2
      # Container 2 configuration

  # Optional: Add volumes and volume mounts if needed
  volumes:
    - name: shared-data
      emptyDir: {}

  # Optional: Add volume mounts to containers if needed
  # volumeMounts:
  #   - name: shared-data
  #     mountPath: /shared-data
  #     readOnly: true