apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
    - name: app-container
      image: your-image:tag
      ports:
        - containerPort: 8080
      readinessProbe:
        httpGet:
          path: /status
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10